"""made colour not null

Revision ID: a8e2df50c232
Revises: 44e168b47148
Create Date: 2025-05-29 11:49:00.725509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e2df50c232'
down_revision = '44e168b47148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('colour',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('colour',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    # ### end Alembic commands ###
